# Shallow Net in Keras

Bulding a Shallow Neural Network to classify MNIST digits.

#### Set seed for reproducibility

In [1]:
import numpy as np
np.random.seed(42)

#### Load dependencies

In [2]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import SGD
from keras import regularizers
from keras.callbacks import TensorBoard

Using TensorFlow backend.


#### Load data

In [3]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [4]:
X_train.shape

(60000, 28, 28)

In [5]:
y_train[0:99]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5, 3, 6, 1, 7, 2, 8, 6, 9, 4, 0, 9,
       1, 1, 2, 4, 3, 2, 7, 3, 8, 6, 9, 0, 5, 6, 0, 7, 6, 1, 8, 7, 9, 3, 9,
       8, 5, 9, 3, 3, 0, 7, 4, 9, 8, 0, 9, 4, 1, 4, 4, 6, 0, 4, 5, 6, 1, 0,
       0, 1, 7, 1, 6, 3, 0, 2, 1, 1, 7, 9, 0, 2, 6, 7, 8, 3, 9, 0, 4, 6, 7,
       4, 6, 8, 0, 7, 8, 3], dtype=uint8)

In [6]:
X_test[0]
y_test[0]

7

In [7]:
y_test.shape

(10000,)

In [8]:
X_test.shape

(10000, 28, 28)

#### Preprocess data
Flatten and normalise input data.

In [9]:
X_train = X_train.reshape(60000, 28 * 28 * 1).astype('float32')
X_test = X_test.reshape(10000, 28 * 28 * 1).astype('float32')

In [10]:
X_train /= 255
X_test /= 255

In [11]:
X_train[0]

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.  

In [12]:
# One-hot encoded categories
n_classes = 10
y_train = keras.utils.to_categorical(y_train, n_classes)
y_test = keras.utils.to_categorical(y_test, n_classes)

In [13]:
y_train[0]

array([ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.])

#### Design Neural Network architecture

In [14]:
# Initialiser: zeros; random; Xavier; and He.
# Regularisers: L2; and Dropout

model = Sequential()
model.add(Dense((1024), activation = 'relu', input_shape = (28 * 28 * 1,)))
model.add(Dropout(.25))
model.add(Dense((1024), activation = 'relu'))
model.add(Dropout(.25))
model.add(Dense((10), activation = 'softmax'))

In [15]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1024)              803840    
_________________________________________________________________
dropout_1 (Dropout)          (None, 1024)              0         
_________________________________________________________________
dense_2 (Dense)              (None, 1024)              1049600   
_________________________________________________________________
dropout_2 (Dropout)          (None, 1024)              0         
_________________________________________________________________
dense_3 (Dense)              (None, 10)                10250     
Total params: 1,863,690
Trainable params: 1,863,690
Non-trainable params: 0
_________________________________________________________________


#### TensorBoard

In [16]:
tensorboard = TensorBoard("../logs/shallownet-mnist-sqrd-error-20-epochs")

#### Configure model

In [17]:
# Loss: Corss Entropy
# Optimiser: Adam
model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

#### Train!

In [18]:
model.fit(X_train, y_train, batch_size = 128, epochs = 20, verbose = 1, validation_split = 0.1, callbacks = [tensorboard])

Train on 54000 samples, validate on 6000 samples
Epoch 1/20
54000/54000 [==============================] - 17s - loss: 0.2324 - acc: 0.9299 - val_loss: 0.0879 - val_acc: 0.9700
Epoch 2/20
54000/54000 [==============================] - 18s - loss: 0.1007 - acc: 0.9687 - val_loss: 0.0797 - val_acc: 0.9752
Epoch 3/20
54000/54000 [==============================] - 24s - loss: 0.0699 - acc: 0.9776 - val_loss: 0.0655 - val_acc: 0.9800
Epoch 4/20
54000/54000 [==============================] - 20s - loss: 0.0577 - acc: 0.9819 - val_loss: 0.0739 - val_acc: 0.9783
Epoch 5/20
54000/54000 [==============================] - 19s - loss: 0.0457 - acc: 0.9856 - val_loss: 0.0628 - val_acc: 0.9823
Epoch 6/20
54000/54000 [==============================] - 19s - loss: 0.0407 - acc: 0.9863 - val_loss: 0.0695 - val_acc: 0.9813
Epoch 7/20
54000/54000 [==============================] - 20s - loss: 0.0374 - acc: 0.9875 - val_loss: 0.0704 - val_acc: 0.9818
Epoch 8/20
54000/54000 [==============================]

#### Test Predictions

In [19]:
predictions = model.predict_classes(X_test, verbose = 2)
print(predictions)

[7 2 1 ..., 4 5 6]


#### Test Final Accuracy

In [20]:
final_loss, final_acc = model.evaluate(X_test, y_test, verbose = 1)
print("Final loss: {0:.4f}, final accuracy: {1:.4f}".format(final_loss, final_acc))

 9728/10000 [============================>.] - ETA: 0sFinal loss: 0.0791, final accuracy: 0.9832
